name: 'Tests'

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/tests.yml'
      - '**.go'
      - 'go.sum'
      - 'go.mod'
  pull_request:
    branches:
      - 'main'

jobs:
  tests:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version-file: 'go.mod'

      - name: "Tests"
        # language=sh
        run: go test ./...